version: '3.8'

services:
  app:
    build:
      context: .
    container_name: fastapi-app
    volumes:
      - ./src:/test_task_fastapi/src
      - ./alembic.ini:/test_task_fastapi/alembic.ini
    env_file:
      - .env

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: postgres_db
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1465
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  celery:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    command: ["celery", "-A", "src.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  pg_data:
  dbdata6: