"""changed user_id percision to 30

Revision ID: 53e183837ac9
Revises: 19d4c6ee08d2
Create Date: 2025-01-22 21:48:20.587836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e183837ac9'
down_revision: Union[str, None] = '19d4c6ee08d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id',
               existing_type=sa.NUMERIC(precision=21, scale=2),
               type_=sa.DECIMAL(precision=30, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id',
               existing_type=sa.DECIMAL(precision=30, scale=2),
               type_=sa.NUMERIC(precision=21, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
