"""added users table

Revision ID: bfe337d070c0
Revises: 53e183837ac9
Create Date: 2025-01-22 23:33:29.129479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe337d070c0'
down_revision: Union[str, None] = '53e183837ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id',
               existing_type=sa.NUMERIC(precision=30, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=30, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
